openapi:
  title: leads_api API
  version: 1.0.0
  description: API gerada automaticamente pelo Vaden.
  enable: true

postgres:
  host: localhost
  database: banco_portal
  port: 5433
  username: postgres
  password: postgres
  ssl: disable
server:
  port: 8080
  host: 0.0.0.0

env:
  base_url: http://localhost:8080/
  mode: debug